### ISSUE TITLE
Water level overlay incorrect detection

### ISSUE THREAD

**Issue by spacewalk01** [gaugecam-dev/GRIME2#1]
Hello thank you for sharing your work. I run your application and it detects the top border line of the board as water level overlay and does not detect actual water level overlay. How can I fix it? Is there any parameter settings for detection algorithm?

**Comment by spacewalk01** [comment]
Also calib boxes are incorrectly detected or set.

**Comment by gaugecam** [comment]
Hello,

There are parameters that can be set, but they have not yet been exposed to the interface. This is a very early version Alpha version of a GUI that runs the underlying calibration and line finding algorithms. We will get to that in due time. If you could email me one of your images, I could take a look and see if there is a way you can use the program to make this work.

Ken

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by spacewalk01** [comment]
Thank you for your reply. I am sorry but I couldn't find your email address on the internet. Would you please let know your email address? Thank you.

**Comment by gaugecam** [comment]
The email I use for this account is kenchapman@protonmail.com.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gaugecam** [comment]
Hello Batselem,

I just wanted to let you know that we have now linked your review on our website. Thank you so much for this good work! 

It is under Citations and Reviews on this page: [GaugeCam](https://gaugecam.org/)
